theme = "kanagawa"

[editor]
color-modes = true
line-number = "relative"
mouse = false
popup-border = "all"
rulers = [100]
text-width = 100
true-color = true
end-of-line-diagnostics = "disable"

[editor.soft-wrap]
# enable = true
# wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
C-u = ["half_page_up", "goto_window_center"]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
C-q = "save_selection"
A-s = "split_selection_on_newline"
C-d = ["half_page_down", "goto_window_center"]
";" = ["flip_selections"]
"," = "repeat_last_motion"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space.z]
b = ":sh zig build"
t = ":sh zig test"
r = ":sh zig run"


